# Generated by Django 4.2.6 on 2023-10-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_parent_reaction_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
